on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'hack/tools/ami/AMIBuildConfig.json'

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

    - name: Set up Go 
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
      with:
        go-version: 1.17

    - name: Presubmit Job
      run: |
        cd hack/tools/ami
        git clone https://github.com/kubernetes-sigs/image-builder.git
        cd image-builder/images/capi
        sed -i 's/capa-ami-/test-capa-ami-/' ./packer/ami/packer.json
        make deps-ami
        cd ../../..
        go run prow/main.go -cleanup
      env:
          AMI_BUILD_CONFIG_FILENAME: "AMIBuildConfig.json"
          AMI_BUILD_CONFIG_DEFAULTS: "AMIBuildConfigDefaults.json"
          AMI_BUILD_SUPPORTED_OS: "amazon-2"
          AMI_BUILD_REGIONS: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_AMI_OWNER_ID: ""
